### ISSUE TITLE
🐛 [Bug]:

### ISSUE THREAD

**Issue by nniculita** [coleam00/Archon#629]
### Archon Version

latest

### Bug Severity

🟢 Low - Minor inconvenience

### Bug Description

When you save a task by specifically modifying the description field using the GUI, the change is saved in Supabase but is not displayed in the GUI. GUI is still loading the old description value from cache. When you edit the title, the change is immediately visible in the GUI.

### Steps to Reproduce

Open a Task, modify the Description, save, open it again - old description still visible. Check the database, new description is saved.

### Expected Behavior

If you edit a task (description field) after save, the new description should be loaded and visible.

### Actual Behavior

as described above - old description persists

### Error Details (if any)

```text
2apiWithEtag.ts:63 [ETag] Cache hit (304) for /projects/f5da5b65-ffb0-48b8-9ec7-ce51c43fbb21/tasks
chunk-LRA7HBEK.js?v=c08001c0:332 Warning: Missing `Description` or `aria-describedby={undefined}` for {DialogContent}.
(anonymous) @ chunk-LRA7HBEK.js?v=c08001c0:332
commitHookEffectListMount @ chunk-RPCDYKBN.js?v=c08001c0:16915
commitPassiveMountOnFiber @ chunk-RPCDYKBN.js?v=c08001c0:18156
commitPassiveMountEffects_complete @ chunk-RPCDYKBN.js?v=c08001c0:18129
commitPassiveMountEffects_begin @ chunk-RPCDYKBN.js?v=c08001c0:18119
commitPassiveMountEffects @ chunk-RPCDYKBN.js?v=c08001c0:18109
flushPassiveEffectsImpl @ chunk-RPCDYKBN.js?v=c08001c0:19490
flushPassiveEffects @ chunk-RPCDYKBN.js?v=c08001c0:19447
commitRootImpl @ chunk-RPCDYKBN.js?v=c08001c0:19416
commitRoot @ chunk-RPCDYKBN.js?v=c08001c0:19277
performSyncWorkOnRoot @ chunk-RPCDYKBN.js?v=c08001c0:18895
flushSyncCallbacks @ chunk-RPCDYKBN.js?v=c08001c0:9119
(anonymous) @ chunk-RPCDYKBN.js?v=c08001c0:18627Understand this warningAI
[Violation] Forced reflow while executing JavaScript took 45ms
apiWithEtag.ts:63 [ETag] Cache hit (304) for /projects
apiWithEtag.ts:63 [ETag] Cache hit (304) for /projects/f5da5b65-ffb0-48b8-9ec7-ce51c43fbb21/tasks
```

### Affected Component

📋 Projects & Tasks (if enabled)

### Browser & OS

Win11 Latest Chrome

### Service Status (check all that are working)

- [x] 🖥️ Frontend UI (http://localhost:3737)
- [ ] ⚙️ Main Server (http://localhost:8181)
- [ ] 🔗 MCP Service (localhost:8051)
- [ ] 🤖 Agents Service (http://localhost:8052)
- [ ] 💾 Supabase Database (connected)

**Comment by leex279** [comment]
=> already fixed in this PR: https://github.com/coleam00/Archon/pull/625

**Comment by nniculita** [comment]
Sameo....changes and then after 5 sec reverts

**Comment by nniculita** [comment]
reinstalled main, rebuilt --no-cache and still shows the same issue - after you edit the task, the changes are visible for about 5sec and then reverts to previous task description.

**Comment by leex279** [comment]
@nniculita there are now 2 branches. one "stable" and the "main" which represents more a beta state. the docs include now the cloning command for "stable" as well. That just as information.

For the main => did you reset the database / execute the complete_setup.sql again, cause there were a lot of database changes, which need to be applied first.

**Comment by leex279** [comment]
In the migrations folder you can find a UPGRADE documentation, which should work, but we already got some users with problems on it.
I personally would recommend to just go with a clean database. As we are still in BETA, things like this are expected and shouldnt be a big problem.

The Team is working on a stable/sophisticated solution for this, which will show directly in the UI and takes care of further migrations in the future, so when we are out of Beta, it should be fine :)

**Comment by nniculita** [comment]
Ok, I will try fresh

**Comment by nniculita** [comment]
The Description update and the priority update are working now.

A few issues though:
1. When you click Add Task (after you already added a task) the fields are not empty, still contain the title and desc of the previous task created.
2. Table view doesn't include/show the Priority
3. Project name cannot be edited? The Project Description is not even displayed and cannot be edited.
4. KanBan 'buckets'/Status cannot be renamed. 
5. I can't add more 'buckets' if needed.

A few additions that could be good: 
6. Docs under Project is needed - I know you are working on it
7. It would be good if the Tasks had more fields, you know, the classic ones --- Bucket (separated from Staus), Progress/Status, owner, Start Date, Due Date, Attachments, Sub Tasks?
8. It would be good if you could schedule notifications for overdue Tasks - and add a Notify field for others to be notified besides the Owner.
